[package]
name    = "nphysics"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[features]
f32 = [ ]
f64 = [ ]
2d  = [ ]
3d  = [ ]
4d  = [ ]

2df32 = [ "2d", "f32" ]
2df64 = [ "2d", "f64" ]
3df32 = [ "3d", "f32" ]
3df64 = [ "3d", "f64" ]
4df32 = [ "4d", "f32" ]
4df64 = [ "4d", "f64" ]

[lib]
name = "nphysics"
path = "src/lib.rs"

[dependencies.ncollide]
git = "https://github.com/sebcrozet/ncollide"
