[package]
name = "nphysics"
version = "0.7.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[workspace]
members = [ "build/nphysics2d", "nphysics_testbed2d", "examples2d",
            "build/nphysics3d", "nphysics_testbed3d", "examples3d" ]