[package]
name    = "nphysics_testbed3d"
version = "0.1.0"
authors = [ "Sébastien Crozet <developer@crozet.re>" ]

[lib]
name = "nphysics_testbed3d"

[dependencies.nphysics]
features = [ "3df32" ]
path = "../.."

[dependencies.time]
git = "https://github.com/rust-lang/time"

[dependencies.kiss3d]
git = "https://github.com/sebcrozet/kiss3d"
